config/routes.rb
Rails.application.routes.draw do

  root 'flights#index'
  resources :flights, only: [:index, :destroy]
  post "/flights/:id/share" => 'flights#share', as: :flight_share


  # New routes for Week 6

  get  '/auth/:provider/callback' => 'sessions#create'
  post '/auth/:provider/callback' => 'sessions#create'


  # This pseudo-route is automatically provided for us by the omniauth gem:
  # get '/auth/:developer' => omniauth gem
  # get '/auth/:provider' => twitter.com

end

app/models/airline.rb
class Airline < ActiveRecord::Base

  has_many :flights
  
end

app/models/flight.rb
class Flight < ActiveRecord::Base

  belongs_to :airline

  def status
    return "LANDED" if estimated_at < DateTime.now
    return "DELAYED" if estimated_at > scheduled_at
    return "ON TIME"
  end

  def share
    require 'twilio-ruby'

    # put your own credentials here
    account_sid = ENV['TWILIO_CLASS_DEMO_ACCOUNT_SID']
    auth_token = ENV['TWILIO_CLASS_DEMO_AUTH_TOKEN']

    # set up a client to talk to the Twilio REST API
    @client = Twilio::REST::Client.new account_sid, auth_token

    obj = @client.account.messages.create({
    	:from => '+12242063763',
      :to => '+18472194848',
      :body => "#{self.airline.name} ##{self.number} will arrive at #{self.estimated_at.strftime("%B %d, %Y  %l:%M %P")}"
    })

    # Rails.logger.info obj.inspect
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def share
    flight = Flight.find(params[:id])
    flight.share
    redirect_to flights_url, notice: "Message sent!"
  end

  def index
    if params[:date]
      date = Date.strptime(params[:date], "%m-%d-%Y")
    else
      date = Date.today
    end

    @flights = Flight.where('DATE(scheduled_at) = ?', date)
    @flights = @flights.order('scheduled_at asc').limit(100)

    respond_to do |format|
      format.html
      format.json do
        render json: @flights
      end
    end
  end

  def destroy
    @flight = Flight.find(params[:id])
    @flight.destroy
    respond_to do |format|
      format.html do
        redirect_to flights_url
      end
      format.js # do the default thing
    end

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/flights/destroy.js.erb
$("#<%= dom_id(@flight) %>").fadeOut();

app/views/flights/index.html.erb
<p>
  <%= link_to "Sign In", "/auth/developer" %>
</p>

<div class="page-header">
  <h1>
    O'Hare Arrivals
    <small><%= DateTime.now.strftime("%B %d, %Y  %l:%M %P")%>
  </h1>
</div>

<div id="flight_count">
  <h4><%= pluralize(@flights.count, 'flight') %>.</h4>
</div>

<div class='table-responsive'>
  <table class="table table-striped table-bordered">
    <thead>
      <tr class="text-center">
        <th>Action</th>
        <th>Flight #</th>
        <th>Carrier</th>
        <th>Origin</th>
        <th>Expected Arrival Time</th>
        <th>Status</th>
      </tr>
    </thead>

    <tbody>
      <% @flights.each do |flight| %>
        <tr id="<%= dom_id(flight) %>"
            class="text-center"
            data-status="<%= flight.status %>">
          <td>
            <%= link_to "Delete", flight, remote: true, class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: "Are you sure?" } %>
            <%= link_to "Share", flight_share_path(flight), method: :post, class: 'btn btn-sm btn-info', data: { confirm: "Are you sure?" } %>
          </td>
          <td><%= flight.airline.abbreviation.upcase %> <%= flight.number %></td>
          <td><%= flight.airline.name %></td>
          <td><%= flight.origin %></td>
          <td><%= flight.estimated_at.strftime("%l:%M %P") if flight.estimated_at.present? %></td>
          <td><%= flight.status %></td>
        </tr>
      <% end %>
    </tbody>

  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flights</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>

  <%= csrf_meta_tags %>

</head>
  <body>

    <div class="container">

      <% if notice.present? %>
        <div class="alert alert-info">
          <%= notice %>
        </div>
      <% end %>

      <%= yield %>


      <!-- Start of StatCounter Code for Default Guide -->
    <script type="text/javascript">
    var sc_project=10678926;
    var sc_invisible=0;
    var sc_security="a97329ce";
    var scJsHost = (("https:" == document.location.protocol) ?
    "https://secure." : "http://www.");
    document.write("<sc"+"ript type='text/javascript' src='" +
    scJsHost+
    "statcounter.com/counter/counter.js'></"+"script>");
    </script>
    <noscript><div class="statcounter"><a title="shopify
    analytics ecommerce" href="http://statcounter.com/shopify/"
    target="_blank"><img class="statcounter"
    src="http://c.statcounter.com/10678926/0/a97329ce/0/"
    alt="shopify analytics ecommerce"></a></div></noscript>
    <!-- End of StatCounter Code for Default Guide -->

  </body>
</html>